/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Reza Aryadi
 */
public class MainMenuDosen extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuDosen
     */
    public MainMenuDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        BuatKelompokTABtn = new javax.swing.JButton();
        TambahAnggotaBtn = new javax.swing.JButton();
        HapusAnggotaTABtn = new javax.swing.JButton();
        JadiDosenPembimbingBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Aplikasi Pengelolaan Tugas Akhir");
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(327, 488));
        jInternalFrame1.setVisible(true);

        BuatKelompokTABtn.setText("Buat Kelompok TA");
        BuatKelompokTABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuatKelompokTABtnActionPerformed(evt);
            }
        });

        TambahAnggotaBtn.setText("Tambah Anggota Kelompok TA");

        HapusAnggotaTABtn.setText("Hapus Anggota Kelompok TA");

        JadiDosenPembimbingBtn.setText("Jadi Dosen Pembimbing");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HapusAnggotaTABtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuatKelompokTABtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TambahAnggotaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JadiDosenPembimbingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(BuatKelompokTABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TambahAnggotaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HapusAnggotaTABtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JadiDosenPembimbingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuatKelompokTABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuatKelompokTABtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuatKelompokTABtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuatKelompokTABtn;
    private javax.swing.JButton HapusAnggotaTABtn;
    private javax.swing.JButton JadiDosenPembimbingBtn;
    private javax.swing.JButton TambahAnggotaBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
public Object getBuatKelompokTABtn{
    return BuatKelompokTABtn;
}
public Object getHapusAnggotaTABtn{
    return HapusAnggotaTABtn;
}
public Object getJadiDosenPembimbingBtn{
    return JadiDosenPembimbingBtn;
}
public Object getTambahAnggotaBtn{
    return TambahAnggotaBtn;
}
    public void addListener(ActionListener e){
    BuatKelompokTABtn.addActionListener(e);
    HapusAnggotaTABtn.addActionListener(e);
    JadiDosenPembimbingBtn.addActionListener(e);
    TambahAnggotaBtn.addActionListener(e);

    }




}
